### ISSUE TITLE
Any info on what versions of Strapi this has been tested up to?

### ISSUE THREAD

**Issue by regiside** [viveakrt/strapi-provider-upload-vimeo#4]
I'm trying to implement this in Strapi 4.11.1 but uploads are just going to the default upload folder rather than to vimeo.

Trying to configure the upload provider on it's own before I incorporate upload-multiple-provider. But 

If I use this format like I'm seeing on other upload providers...

```
upload: {
    config: {
      provider: "vimeo",
```
I get: 
`TypeError: provider.init is not a function`

Any info would be great, thanks.

**Comment by viveakrt** [comment]
However, it seems that the format you are using is not supported in this version.
The error message "TypeError: provider.init is not a function" suggests that the "vimeo" provider initialization is not recognized in Strapi 4.11.1.

But this plugin supports 3.6 version of strapi

Alternatively, you can explore other solutions or plugins that are compatible with Strapi 4.11.1 to achieve the desired functionality of uploading files to Vimeo. Checking the official Strapi documentation, community forums, or reaching out to the Strapi support team may provide you with more specific guidance and alternatives for achieving your upload requirements in Strapi 4.11.1.

**Comment by FindMyMission** [comment]
Okay thanks for letting me know! Would be great if there was somewhere where the compatible versions of strapi could be found in the readme or somewhere prominent.

**Comment by regiside** [comment]
Okay thanks for letting me know! Would be great if there was somewhere where the compatible versions of Strapi could be found in the readme or somewhere prominent.
